language: go
branches:
  only:
  - master
go:
- '1.13'
sudo: false
env:
  global:
  - GH_REPO="github.com/jackysp/jackysp.github.io.git"
  - secure: OriDmoKnKioAAQKzlM8NogShWsXX7M/tp5xwEIIiMHybZWorxp/z879ovUUBg6jx5U6HK6horemdRvBzPRCcDBcBKH8gP03syT7VoL1tlrb87WaxsgnxtSZo8K3oqOKaoWhtb3pHTgtHt52stS4Py1KllFbcWZ3nivqhdzFxEVfhln9YpB15SeuX8xQpUHv+v431XSFMBk3ctET5YiZ2Owyq+vReDW8cCDnngsYjyHlBZsGZnoOf5OjXvXBn2M8X9N92fuQMk61/EVvFzDe0pv9/Z94QR13wdBFQOGjPNqk9Iql4c0CQzx6Pqkq/dJ01Nrr70xBlF1ivAGallplUU2Km53dszPVH4jy0YEWyy0LGKFnK9u9dauGCMszF5VSVD0YQOo0DUVdeJe3ckZbB+kKeA4rfuoUeBDAsSTpdE7wodkwV0M7Gqdnl3Jqvo7PPkWCauaSF/7ldmYUnjlbi/hXlo6SsyQIP5gl6tg6g2nkqnLrsCDb5CNyRvMko/JvGtOyy9rB29hu0Y35amITZeOxCO2WdjoP+WpOzpajnuje5hSLSCNFgEiu9NdUYGSOwvjYhlfxeXrsxFwbpQyxHYq0Gp1z+7aszMB5ZRwG0yux25symU+OqsS6zm7iloQtoGBMiCVyDVWlWK40ctL86IovOHa6KpUVH0kvMFUR11vM=
before_script:
- git clone https://${GH_TOKEN}@${GH_REPO} public
script:
- make
after_success:
- MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- cd public
- git config user.email "jackysp@gmail.com"
- git config user.name "Jack Yu"
- git add --all
- git commit -m "${MESSAGE}"
- git push --force origin master
