baseURL = "http://blog.minifish.org/"
languageCode = "en-US"
title = "Mini Fish"
disqusShortname = "jackysp"
theme = "hyde"
#summaryLength = 0 # show summary by default length
hasCJKLanguage = false

[Menus]
    main = [
      {Name = "Github", URL = "https://github.com/jackysp/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/shuaipeng-yu-81280434/"}
    ]

[params]
    description = "A blog that's all about how to do it."
    #themeColor = "theme-base-0d" # use the default color
    layoutReverse = true
