baseURL = "https://blog.minifish.org/"
copyright = "© Mini Fish 2014-present"
languageCode = "en-US"
title = "Mini Fish"
theme = "PaperMod"
enableRobotsTXT = true
enableEmoji = true
#summaryLength = 0 # show summary by default length
#hasCJKLanguage = false

[menus]
  [[menus.main]]
    name = "Search"
    url = "/search/"
  [[menus.main]]
    name = "Archive"
    url = "/archives/"

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  defaultTheme = "auto"
  description = "A Collection of Straightforward HOW-TO Guides"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = true
  hidemeta = false
  hideSummary = false
  ShowPageNums = true
  showtoc = true
  tocopen = false
  ShowFullTextinRSS = true
  author = "Jack Yu"

  [params.homeInfoParams]
    Title = "Hi there 👋"
    Content = "Welcome to my blog site. I am a software engineer and I write about programming, software development, and all things tech. I hope you find something useful here."

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/jackysp"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jackysp"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/shuaipeng-yu-81280434/"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:i@minifish.org"

  [params.editPost]
    URL = "https://github.com/jackysp/blog/tree/master/content"
    Text = "Suggest Changes" # edit text
    appendFilePath = true # to append file path to Edit link

[services]
  [services.disqus]
    shortname = "jackysp"
  [services.googleAnalytics]
    id = "G-G0H8JF722Y"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16*16.png"
  favicon32x32 = "/favicon-32*32.png"
  apple_touch_icon = "/apple-touch-icon.png"
  safari_pinned_tab = "/favicon.svg"
