baseURL = "http://blog.minifish.org/"
languageCode = "en-US"
title = "Mini Fish"
#disqusShortname = "jackysp"
theme = "hyde"
#summaryLength = 0 # show summary by default length
hasCJKLanguage = false

[Menus]
    main = [
      {Name = "GitHub", URL = "https://github.com/jackysp/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/shuaipeng-yu-81280434/"}
    ]

[params]
    description = "A collection of straightforward how-to guides."
    #themeColor = "theme-base-0d" # use the default color

[services]
  [services.disqus]
    shortname = 'jackysp'
  [services.googleAnalytics]
    id = 'G-G0H8JF722Y'